import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import type { AddressInfo } from 'node:net';
import { URL } from 'node:url';
import fs from 'node:fs';
import path from 'node:path';

import { FAVICON_BUFFER, FAVICON_DATA_URI } from './favicon.js';

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import { randomUUID } from 'node:crypto';
import { registerAppTool, RESOURCE_MIME_TYPE } from '@modelcontextprotocol/ext-apps/server';
import type { RegisteredResource, RegisteredTool } from '@modelcontextprotocol/sdk/server/mcp.js';

import { z } from 'zod';
import { type MCPServerConfig, type MCPServerHandle, type SimulationWithDist } from './types.js';
import { injectResolvedDomain, injectDefaultDomain } from './resolve-domain.js';

export type { MCPServerConfig, MCPServerHandle, SimulationWithDist } from './types.js';

// Dev server URLs for Vite HMR (localhost only — used for direct connections like ChatGPT).
// Mutable: updated by runMCPServer once the actual port is known.
let localDevServerUrl = 'http://localhost:8000';
let localHmrWsUrl = 'ws://localhost:24678';

/**
 * Detect whether this request needs pre-built HTML (no Vite HMR).
 *
 * Claude's iframe sandbox blocks HTTP script sources, so it can't load from the
 * local Vite dev server. We detect Claude by its user-agent and serve the
 * self-contained production build instead.
 *
 * ChatGPT also connects through tunnels but its browser can reach localhost via
 * the local-network-access permission, so it gets Vite HMR.
 */
function needsProdBuild(headers: Record<string, string | string[] | undefined>): boolean {
  const ua = headers['user-agent'];
  const userAgent = typeof ua === 'string' ? ua : Array.isArray(ua) ? ua[0] : '';
  return /claude/i.test(userAgent ?? '');
}

/**
 * Read pre-built resource HTML (production mode).
 * The HTML file is generated by `sunpeak build` with JS and CSS inlined.
 */
function readResourceHtmlProd(distPath: string): string {
  const htmlPath = path.resolve(distPath);

  if (!fs.existsSync(htmlPath)) {
    throw new Error(
      `Resource HTML file not found at ${htmlPath}. Run "sunpeak build" to generate the built app.`
    );
  }

  return fs.readFileSync(htmlPath, 'utf8');
}

/**
 * Generate HTML that loads from Vite dev server with HMR.
 * Used for direct connections (e.g. ChatGPT connecting to localhost).
 */
function getViteResourceHtml(srcPath: string): string {
  // Extract component name from path:
  //   /src/resources/albums/albums.tsx -> AlbumsResource
  const rawFileName = srcPath.split('/').pop() ?? '';
  const fileName = rawFileName.replace(/\.tsx$/, '');
  const componentName =
    fileName
      .split('-')
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join('') + 'Resource';

  const devServerUrl = localDevServerUrl;

  // Encode srcPath and componentName for the virtual entry module
  const entryParams = new URLSearchParams({ src: srcPath, component: componentName });
  // Vite serves virtual modules via /@id/ prefix
  const virtualModuleUrl = `${devServerUrl}/@id/virtual:sunpeak-entry?${entryParams.toString()}`;

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <script type="module">
    import { injectIntoGlobalHook } from "${devServerUrl}/@react-refresh";
    injectIntoGlobalHook(window);
    window.$RefreshReg$ = () => {};
    window.$RefreshSig$ = () => (type) => type;
    window.__vite_plugin_react_preamble_installed__ = true;
  </script>
  <script type="module" src="${devServerUrl}/@vite/client"></script>
  <script type="module">
    (async () => {
      if (!navigator.permissions?.query) return;
      const protocol = window.location.protocol;
      if (protocol !== 'http:' && protocol !== 'https:') return;
      const host = window.location.hostname;
      const isLoopback = host === 'localhost' || /^127\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})$/.test(host) || host === '::1';
      if (isLoopback) return;
      try {
        const status = await navigator.permissions.query({ name: "local-network-access" });
        if (status.state === "denied") {
          document.getElementById('root').innerHTML = '<div style="background:#fef2f2;border:2px solid #ef4444;border-radius:8px;padding:16px;text-align:center;font-family:system-ui,sans-serif;"><div style="color:#ef4444;font-size:18px;font-weight:600;margin-bottom:8px;">Local network access permission is denied</div><div style="color:#ef4444;font-size:14px;">Please enable it in your browser settings. <a href="https://developer.chrome.com/blog/local-network-access" target="_blank" style="color:#ef4444;text-decoration:underline;">Learn more</a></div></div>';
        }
      } catch (e) {}
    })();
  </script>
  <div id="root"></div>
  <script type="module" src="${virtualModuleUrl}"></script>
</body>
</html>`;
}

/**
 * Get resource HTML content.
 *
 * - Direct connections (ChatGPT): Vite dev server HTML with HMR
 * - Tunnel connections (Claude via ngrok): Pre-built HTML with everything inlined
 */
function getResourceHtml(
  simulation: SimulationWithDist,
  viteMode: boolean,
  prodBuild: boolean
): string {
  if (viteMode && simulation.srcPath && !prodBuild) {
    return getViteResourceHtml(simulation.srcPath);
  }
  return readResourceHtmlProd(simulation.distPath!);
}

/**
 * Inject localhost Vite dev server URLs into CSP metadata.
 * Only needed for direct connections where the iframe loads scripts from localhost.
 */
function injectViteCSP(existingMeta: Record<string, unknown> | undefined): Record<string, unknown> {
  const meta = existingMeta ?? {};
  const ui = (meta.ui as Record<string, unknown>) ?? {};
  const csp = (ui.csp as Record<string, unknown>) ?? {};

  const existingResourceDomains = (csp.resourceDomains as string[]) ?? [];
  const resourceDomains = existingResourceDomains.includes(localDevServerUrl)
    ? existingResourceDomains
    : [...existingResourceDomains, localDevServerUrl];

  const existingConnectDomains = (csp.connectDomains as string[]) ?? [];
  const connectDomains = [...existingConnectDomains];
  if (!connectDomains.includes(localDevServerUrl)) connectDomains.push(localDevServerUrl);
  if (!connectDomains.includes(localHmrWsUrl)) connectDomains.push(localHmrWsUrl);

  return {
    ...meta,
    ui: {
      ...ui,
      csp: { ...csp, resourceDomains, connectDomains },
    },
  };
}

type AppServerResult = {
  server: McpServer;
  resourceHandles: Map<string, RegisteredResource>;
  toolHandles: {
    handle: RegisteredTool;
    resourceName: string;
    toolMeta: Record<string, unknown>;
  }[];
};

// Server-startup timestamp for cache-busting resource URIs.
// Stable within a dev server session (so ChatGPT cross-session reads work)
// but changes on restart so Claude picks up rebuilt resources.
const startupTimestamp = Date.now().toString(36);

function createAppServer(
  config: MCPServerConfig,
  simulations: SimulationWithDist[],
  viteMode: boolean
): AppServerResult {
  const { name = 'sunpeak-app', version = '0.1.0', serverInfo } = config;

  const mcpServer = new McpServer(
    {
      name: serverInfo?.name ?? name,
      version: serverInfo?.version ?? version,
      ...(serverInfo?.title ? { title: serverInfo.title } : {}),
      ...(serverInfo?.description ? { description: serverInfo.description } : {}),
      ...(serverInfo?.websiteUrl ? { websiteUrl: serverInfo.websiteUrl } : {}),
      icons: serverInfo?.icons ?? [
        {
          src: FAVICON_DATA_URI,
          mimeType: 'image/png',
          sizes: ['64x64'],
        },
      ],
    },
    { capabilities: { resources: {}, tools: {} } }
  );

  // Capture the connecting host's clientInfo.name after MCP initialization.
  // Read callbacks close over this variable to resolve host-specific domain maps.
  // Also update listing-level _meta on all resources so that `resources/list`
  // returns the resolved domain (hosts like ChatGPT check domain from the listing).
  let clientName: string | undefined;
  mcpServer.server.oninitialized = () => {
    clientName = mcpServer.server.getClientVersion()?.name;

    for (const [, handle] of resourceHandles) {
      const currentMeta = handle.metadata?._meta as Record<string, unknown> | undefined;
      const resolved = injectResolvedDomain(currentMeta, clientName) ?? currentMeta;
      const withDefault = injectDefaultDomain(resolved, clientName, localDevServerUrl);
      if (withDefault !== resolved) {
        handle.update({ metadata: { ...handle.metadata, _meta: withDefault } });
      }
    }
  };

  // Track registered resource URIs and tool names to avoid duplicate registration
  // (multiple simulations can share the same resource or tool, e.g. review-diff and review-post)
  const registeredUriSet = new Set<string>();
  const registeredToolNames = new Set<string>();
  const resourceHandles = new Map<string, RegisteredResource>();
  const toolHandles: AppServerResult['toolHandles'] = [];

  // Register each simulation's tool and resource
  for (const simulation of simulations) {
    const resource = simulation.resource;
    const tool = simulation.tool;
    const toolResult = simulation.toolResult ?? { structuredContent: null };
    const toolMeta = (tool._meta as Record<string, unknown>) ?? {};

    if (resource) {
      // ── UI tool: register resource + tool via ext-apps helper ──

      // Derive a URI from the resource name with a startup timestamp for cache-busting.
      // Stable within a dev server session (ChatGPT reads URIs from tools/list in one
      // session and fetches content in another), but changes on restart so hosts like
      // Claude pick up rebuilt resources.
      const uri = (resource.uri as string) ?? `ui://${resource.name as string}-${startupTimestamp}`;
      const resourceName = resource.name as string;
      const resourceMeta = (resource._meta as Record<string, unknown>) ?? {};

      // Register the resource directly via SDK (not ext-apps wrapper) to capture the
      // RegisteredResource handle for URI updates on rebuild (cache-busting).
      if (!registeredUriSet.has(uri)) {
        registeredUriSet.add(uri);
        const listMeta = viteMode ? injectViteCSP(resourceMeta) : resourceMeta;
        const handle = mcpServer.registerResource(
          resourceName,
          uri,
          {
            mimeType: RESOURCE_MIME_TYPE,
            description: resource.description as string | undefined,
            _meta: listMeta,
          },
          async (
            readUri: URL,
            extra: { requestInfo?: { headers?: Record<string, string | string[] | undefined> } }
          ) => {
            // Claude's sandbox blocks HTTP script sources, so serve pre-built HTML.
            // ChatGPT can reach localhost, so it gets Vite HMR.
            const prodBuild = needsProdBuild(
              (extra?.requestInfo?.headers as Record<string, string | string[] | undefined>) ?? {}
            );
            const baseMeta = viteMode && !prodBuild ? injectViteCSP(resourceMeta) : resourceMeta;
            const resolvedMeta = injectResolvedDomain(baseMeta, clientName) ?? baseMeta;
            const readMeta = injectDefaultDomain(resolvedMeta, clientName, localDevServerUrl);

            let content: string;
            try {
              content = getResourceHtml(simulation, viteMode, prodBuild);
            } catch (error) {
              console.error(`[MCP] ReadResource error for ${readUri.href}:`, error);
              throw error;
            }
            const sizeKB = (content.length / 1024).toFixed(1);
            const servedVite = viteMode && simulation.srcPath && !prodBuild;
            console.log(
              `[MCP] ReadResource: ${readUri.href} → ${sizeKB}KB${servedVite ? ' (vite)' : ' (built)'}`
            );

            return {
              contents: [
                {
                  // Use readUri (not closure variable) so the response URI matches after updates
                  uri: readUri.href,
                  mimeType: RESOURCE_MIME_TYPE,
                  text: content,
                  _meta: readMeta,
                },
              ],
            };
          }
        );
        resourceHandles.set(resourceName, handle);
      }

      // Register the tool using ext-apps helper (normalizes ui/resourceUri metadata).
      // Capture the returned RegisteredTool handle for metadata updates on rebuild.
      // Use passthrough schema so the MCP SDK forwards all arguments to the handler
      // without stripping. Can't use the tool's own Zod schema because it's loaded
      // via Vite SSR from a different Zod module instance.
      const fullToolMeta = {
        ...toolMeta,
        ui: {
          resourceUri: uri,
          // Preserve tool visibility from simulation metadata if declared
          ...((toolMeta.ui as Record<string, unknown>)?.visibility
            ? { visibility: (toolMeta.ui as Record<string, unknown>).visibility }
            : {}),
        },
      };
      const toolHandle = registerAppTool(
        mcpServer,
        tool.name as string,
        {
          description: tool.description as string | undefined,
          inputSchema: z.object({}).passthrough(),
          ...(simulation.outputSchema
            ? {
                outputSchema: simulation.outputSchema as Parameters<
                  typeof registerAppTool
                >[2]['outputSchema'],
              }
            : {}),
          annotations: tool.annotations as Record<string, unknown> | undefined,
          _meta: fullToolMeta,
        },
        async (args: Record<string, unknown>, extra) => {
          const argKeys = Object.keys(args);
          const argsStr = argKeys.length > 0 ? `{${argKeys.join(', ')}}` : '{}';

          // When prodTools is enabled (--prod-tools flag), always use the real
          // handler so ChatGPT/Claude get live results. Otherwise, prefer simulation
          // mock data for UI tools so external hosts get predictable fixture results.
          // Backend-only tools (no structuredContent) always use real handlers.
          const hasMockResult = toolResult?.structuredContent != null;
          const realHandler = simulation.handler;
          const useLiveHandler = realHandler && (config.prodTools || !hasMockResult);

          if (useLiveHandler) {
            console.log(`[MCP] CallTool: ${tool.name}${argsStr} → live handler`);
            try {
              const result = await (
                realHandler as (args: Record<string, unknown>, extra: unknown) => unknown
              )(args, extra);
              if (typeof result === 'string') {
                return { content: [{ type: 'text' as const, text: result }] };
              }
              return result as { content: { type: 'text'; text: string }[] };
            } catch (error) {
              const msg = error instanceof Error ? error.message : String(error);
              console.error(`[MCP] CallTool error (${tool.name}): ${msg}`);
              return {
                content: [{ type: 'text' as const, text: `Error: ${msg}` }],
                isError: true,
              };
            }
          }

          console.log(
            `[MCP] CallTool: ${tool.name}${argsStr} → ${hasMockResult ? 'structured' : 'text'}`
          );

          return {
            content: [
              {
                type: 'text' as const,
                text: `Rendered ${tool.description}!`,
              },
            ],
            structuredContent:
              (toolResult?.structuredContent as Record<string, unknown>) ?? undefined,
          };
        }
      );
      toolHandles.push({ handle: toolHandle, resourceName, toolMeta: fullToolMeta });
    } else if (!registeredToolNames.has(tool.name as string)) {
      registeredToolNames.add(tool.name as string);
      // ── Plain tool (no UI): register directly via mcpServer ──
      // Use the real handler if available (loaded via Vite SSR in dev mode),
      // otherwise fall back to mock response from simulation data.
      //
      // Use a passthrough Zod schema so the MCP SDK passes args to the handler.
      // We can't use the tool's own Zod schema because it's loaded via Vite SSR
      // from a different Zod module instance, causing isZodSchemaInstance checks
      // to fail. A passthrough schema from the same Zod instance as the SDK
      // accepts any arguments and forwards them to the handler.
      const realHandler = simulation.handler;
      const plainToolConfig: Record<string, unknown> = {
        description: tool.description as string | undefined,
        // Use passthrough so the SDK passes all args to the handler without stripping.
        // We can't use the tool's own Zod schema because it's loaded via Vite SSR
        // from a different Zod module instance, causing isZodSchemaInstance checks to fail.
        inputSchema: z.object({}).passthrough(),
        ...(simulation.outputSchema ? { outputSchema: simulation.outputSchema } : {}),
        annotations: tool.annotations as Record<string, unknown> | undefined,
        _meta: toolMeta,
      };
      (mcpServer.registerTool as (...a: unknown[]) => unknown)(
        tool.name as string,
        plainToolConfig,
        async (args: Record<string, unknown>, extra: unknown) => {
          const argKeys = Object.keys(args);
          const argsStr = argKeys.length > 0 ? `{${argKeys.join(', ')}}` : '{}';
          console.log(`[MCP] CallTool: ${tool.name}${argsStr}`);

          if (realHandler) {
            try {
              const result = await realHandler(args, extra);
              if (typeof result === 'string') {
                return { content: [{ type: 'text' as const, text: result }] };
              }
              return result as { content: { type: 'text'; text: string }[] };
            } catch (error) {
              console.error(`[MCP] Handler error for ${tool.name}:`, error);
              return {
                isError: true,
                content: [
                  {
                    type: 'text' as const,
                    text: `Error: ${error instanceof Error ? error.message : String(error)}`,
                  },
                ],
              };
            }
          }

          // Fallback: mock response from simulation data
          return {
            content: [
              {
                type: 'text' as const,
                text: `Called ${tool.description}!`,
              },
            ],
            structuredContent:
              (toolResult?.structuredContent as Record<string, unknown>) ?? undefined,
          };
        }
      );
    }
  }

  const uiToolCount = simulations.filter((s) => s.resource).length;
  const plainToolCount = simulations.length - uiToolCount;
  console.log(
    `[MCP] Registered ${simulations.length} tool(s) (${uiToolCount} UI, ${plainToolCount} plain), ${registeredUriSet.size} resource(s)`
  );

  return { server: mcpServer, resourceHandles, toolHandles };
}

type SessionRecord = {
  server: McpServer;
  transport: StreamableHTTPServerTransport;
  /** True for localhost connections (ChatGPT, inspector) — they use Vite HMR. */
  isLocal: boolean;
  lastActivity: number;
  /** Resource handles for URI cache-busting on rebuild. Keyed by resource name. */
  resourceHandles: Map<string, RegisteredResource>;
  /** Tool handles for metadata cache-busting on rebuild. */
  toolHandles: AppServerResult['toolHandles'];
};

/** How long an idle session lives before being cleaned up (5 minutes). */
const SESSION_IDLE_TIMEOUT_MS = 5 * 60 * 1000;

/**
 * Check if the request originates from localhost.
 * Local connections (ChatGPT, inspector) use Vite HMR for live content updates.
 */
function isLocalConnection(req: IncomingMessage): boolean {
  const addr = req.socket.remoteAddress;
  return addr === '127.0.0.1' || addr === '::1' || addr === '::ffff:127.0.0.1';
}

const sessions = new Map<string, SessionRecord>();

const MCP_PATH = '/mcp';

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS',
  'Access-Control-Allow-Headers':
    'content-type, accept, authorization, mcp-session-id, ngrok-skip-browser-warning',
  'Access-Control-Expose-Headers': 'mcp-session-id',
} as const;

// Periodically clean up idle sessions.
// Closing the server triggers transport.onclose which handles session map cleanup.
const cleanupInterval = setInterval(() => {
  const now = Date.now();
  for (const [id, session] of sessions) {
    if (now - session.lastActivity > SESSION_IDLE_TIMEOUT_MS) {
      console.log(`[MCP] Session expired: ${id.substring(0, 8)}...`);
      void session.server.close();
    }
  }
}, 60_000);
cleanupInterval.unref();

async function handleMcpRequest(
  req: IncomingMessage,
  res: ServerResponse,
  config: MCPServerConfig,
  simulations: SimulationWithDist[],
  viteMode: boolean
) {
  // Set CORS headers for all MCP responses
  for (const [key, value] of Object.entries(CORS_HEADERS)) {
    res.setHeader(key, value);
  }

  // Parse body for POST requests
  let parsedBody: unknown;
  if (req.method === 'POST') {
    const chunks: Buffer[] = [];
    await new Promise<void>((resolve, reject) => {
      req.on('data', (chunk: Buffer | string) => {
        chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk as string));
      });
      req.on('end', resolve);
      req.on('error', reject);
    });
    const rawBody = Buffer.concat(chunks).toString('utf8');
    try {
      parsedBody = JSON.parse(rawBody);
      const parsed = parsedBody as { method?: string; params?: Record<string, unknown> };
      if (parsed.method) {
        const sid = req.headers['mcp-session-id'] as string | undefined;
        const sidStr = sid ? ` (${sid.substring(0, 8)}...)` : '';
        const extra =
          parsed.method === 'resources/read' ? ` uri=${JSON.stringify(parsed.params?.uri)}` : '';
        console.log(`[MCP] ← ${parsed.method}${extra}${sidStr}`);
      }
    } catch {
      res.writeHead(400).end('Invalid JSON');
      return;
    }
  }

  const sessionId = req.headers['mcp-session-id'] as string | undefined;

  // Route to existing session
  if (sessionId) {
    const session = sessions.get(sessionId);
    if (!session) {
      res.writeHead(404).end('Unknown session');
      return;
    }
    session.lastActivity = Date.now();
    await session.transport.handleRequest(req, res, parsedBody);
    return;
  }

  // New session (POST without session ID = initialization)
  if (req.method === 'POST') {
    const isLocal = isLocalConnection(req);
    const { server, resourceHandles, toolHandles } = createAppServer(config, simulations, viteMode);
    const transport = new StreamableHTTPServerTransport({
      sessionIdGenerator: () => randomUUID(),
      onsessioninitialized: (id) => {
        sessions.set(id, {
          server,
          transport,
          isLocal,
          lastActivity: Date.now(),
          resourceHandles,
          toolHandles,
        });
        const origin = isLocal ? 'local' : 'tunnel';
        console.log(
          `[MCP] Session started: ${id.substring(0, 8)}... (${origin}, ${sessions.size} active)`
        );
      },
      onsessionclosed: (id) => {
        sessions.delete(id);
        console.log(`[MCP] Session closed: ${id.substring(0, 8)}... (${sessions.size} active)`);
      },
    });

    transport.onerror = (error: Error) => {
      // Claude's client probes with an Accept header that doesn't include text/event-stream,
      // then retries correctly. Downgrade this expected negotiation error to a warning.
      if (error.message?.includes('Not Acceptable')) {
        console.warn(`[MCP] Accept header negotiation (expected with some clients)`);
        return;
      }
      const id = transport.sessionId;
      console.error(`[MCP] Transport error${id ? ` (${id.substring(0, 8)}...)` : ''}:`, error);
    };

    transport.onclose = () => {
      const id = transport.sessionId;
      if (id && sessions.has(id)) {
        sessions.delete(id);
        console.log(`[MCP] Session closed: ${id.substring(0, 8)}... (${sessions.size} active)`);
      }
    };

    await server.connect(transport);
    await transport.handleRequest(req, res, parsedBody);
    return;
  }

  // No session ID and not POST → invalid
  res.writeHead(400).end('Bad Request: session ID required');
}

// Type for Vite dev server (minimal interface we need)
interface ViteDevServer {
  middlewares: {
    (req: IncomingMessage, res: ServerResponse, next?: () => void): void;
  };
  ws: {
    handleUpgrade: (
      request: IncomingMessage,
      socket: import('node:stream').Duplex,
      head: Buffer
    ) => void;
  };
}

/**
 * Run the MCP server with the specified configuration.
 *
 * @param config - Server configuration with simulations.
 * @returns Handle for controlling the running server (e.g. cache invalidation).
 */
export function runMCPServer(config: MCPServerConfig): MCPServerHandle {
  const portEnv = Number(process.env.PORT ?? 8000);
  const port = config.port ?? (Number.isFinite(portEnv) ? portEnv : 8000);
  const { simulations } = config;

  // Update module-level URLs so resource HTML and CSP point to the right ports.
  // These are read lazily (on request), so updating them before listen is fine.
  localDevServerUrl = `http://localhost:${port}`;
  if (config.hmrPort) {
    localHmrWsUrl = `ws://localhost:${config.hmrPort}`;
  }

  // Check if Vite dev server is provided
  const viteServer = config.viteServer as ViteDevServer | undefined;
  const viteMode = !!viteServer;

  const httpServer = createServer(async (req: IncomingMessage, res: ServerResponse) => {
    if (!req.url) {
      res.writeHead(400).end('Missing URL');
      return;
    }

    const url = new URL(req.url, `http://${req.headers.host ?? 'localhost'}`);

    // CORS preflight for all routes
    if (req.method === 'OPTIONS') {
      res.writeHead(204, CORS_HEADERS);
      res.end();
      return;
    }

    // Root path (ChatGPT checks this before fetching favicon)
    if (req.method === 'GET' && url.pathname === '/') {
      res.writeHead(200, {
        'Content-Type': 'text/html',
        'Access-Control-Allow-Origin': '*',
      });
      res.end(`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<link rel="icon" type="image/png" href="/favicon.png" />
<title>Sunpeak MCP Server</title>
</head>
<body><h1>Sunpeak MCP Server</h1><p>Connect via <a href="/mcp">/mcp</a></p></body>
</html>`);
      return;
    }

    // Favicon endpoint — serve PNG at /favicon.png and /favicon.ico only.
    // Do NOT serve PNG data at /favicon.svg — returning the wrong content type (image/png
    // for a .svg path) confuses host icon resolvers that dispatch on extension.
    // Support both GET and HEAD — ChatGPT sends HEAD to check existence before fetching.
    if (
      (req.method === 'GET' || req.method === 'HEAD') &&
      (url.pathname === '/favicon.png' || url.pathname === '/favicon.ico')
    ) {
      res.writeHead(200, {
        'Content-Type': 'image/png',
        'Content-Length': FAVICON_BUFFER.length,
        'Cache-Control': 'public, max-age=86400',
        'Access-Control-Allow-Origin': '*',
      });
      res.end(req.method === 'HEAD' ? undefined : FAVICON_BUFFER);
      return;
    }

    // MCP endpoint (Streamable HTTP transport)
    if (url.pathname === MCP_PATH) {
      await handleMcpRequest(req, res, config, simulations, viteMode);
      return;
    }

    // If Vite server is available, delegate all other requests to it
    if (viteServer) {
      // Add CORS headers for Vite-served content (needed for cross-origin widget loading)
      res.setHeader('Access-Control-Allow-Origin', '*');
      res.setHeader('Access-Control-Allow-Headers', 'content-type, ngrok-skip-browser-warning');
      viteServer.middlewares(req, res);
      return;
    }

    // No Vite server, return 404 for non-MCP routes
    console.log(`[HTTP] ${req.method} ${url.pathname} → 404`);
    res.writeHead(404).end('Not Found');
  });

  // Handle WebSocket upgrades for Vite HMR
  if (viteServer) {
    httpServer.on('upgrade', (request, socket, head) => {
      // Forward all WebSocket upgrades to Vite (it handles /@vite/ws)
      viteServer.ws.handleUpgrade(request, socket, head);
    });
  }

  httpServer.on('clientError', (err: NodeJS.ErrnoException, socket) => {
    // ECONNRESET is normal when clients (browser tabs, Playwright) close
    // connections abruptly. Don't log these as errors.
    if (err.code !== 'ECONNRESET') {
      console.error('HTTP client error', err);
    }
    socket.end('HTTP/1.1 400 Bad Request\r\n\r\n');
  });

  // Promise that resolves when the HTTP server is listening.
  let resolveReady: () => void;
  const ready = new Promise<void>((resolve) => {
    resolveReady = resolve;
  });

  const onListening = () => {
    const actualPort = (httpServer.address() as AddressInfo).port;
    // Update module-level URL in case the OS assigned a different port
    localDevServerUrl = `http://localhost:${actualPort}`;
    console.log(`Sunpeak MCP server listening on http://localhost:${actualPort}`);
    console.log(`  MCP endpoint: http://localhost:${actualPort}${MCP_PATH}`);
    if (viteMode) {
      console.log(`  Vite HMR: enabled (source files served with hot reload)`);
    }
    resolveReady!();
  };

  httpServer.on('error', (err: NodeJS.ErrnoException) => {
    if (err.code === 'EADDRINUSE') {
      console.warn(`Port ${port} in use, finding an available port...`);
      // onListening is already registered as a .once('listening') from the first .listen() call
      httpServer.listen(0);
    } else {
      throw err;
    }
  });

  httpServer.listen(port, onListening);

  // Graceful shutdown handler
  const shutdown = async () => {
    console.log('\nShutting down MCP server...');

    httpServer.close(() => {
      console.log('MCP server closed');
      process.exit(0);
    });

    // Force close after 5 seconds if graceful shutdown fails
    setTimeout(() => {
      console.error('Force closing MCP server');
      process.exit(1);
    }, 5000);
  };

  process.on('SIGTERM', () => void shutdown());
  process.on('SIGINT', () => void shutdown());

  return {
    ready,
    invalidateResources() {
      if (sessions.size === 0) return;

      // Only cache-bust non-local (tunnel) sessions. Local sessions (ChatGPT,
      // inspector) use Vite HMR for live content updates — their
      // iframes auto-update without needing a new readResource URI.
      // Tunnel sessions (Claude via ngrok) serve pre-built HTML snapshots, so
      // they need a new URI to force the host to re-read the resource.
      const tunnelSessions = [...sessions].filter(([, s]) => !s.isLocal);
      if (tunnelSessions.length === 0) return;

      const timestamp = Date.now().toString(36);
      for (const [, session] of tunnelSessions) {
        // Update resource URIs with timestamp to force cache-busting.
        // .update() automatically sends resources/list_changed notification.
        for (const [name, handle] of session.resourceHandles) {
          handle.update({ uri: `ui://${name}-${timestamp}` });
        }
        // Update tool metadata to reference the new resource URIs.
        // .update() automatically sends tools/list_changed notification.
        for (const { handle, resourceName, toolMeta } of session.toolHandles) {
          const newUri = `ui://${resourceName}-${timestamp}`;
          handle.update({
            _meta: {
              ...toolMeta,
              ui: { ...(toolMeta.ui as Record<string, unknown>), resourceUri: newUri },
              'ui/resourceUri': newUri,
            },
          });
        }
      }
      console.log(
        `[MCP] Cache-busted ${tunnelSessions.length} tunnel session(s) with timestamp ${timestamp}`
      );
    },
  };
}
