import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { URL } from 'node:url';
import fs from 'node:fs';
import path from 'node:path';

import { FAVICON_BASE64, FAVICON_BUFFER } from './favicon.js';

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import { randomUUID } from 'node:crypto';
import { registerAppTool, RESOURCE_MIME_TYPE } from '@modelcontextprotocol/ext-apps/server';
import type { RegisteredResource, RegisteredTool } from '@modelcontextprotocol/sdk/server/mcp.js';

import { type MCPServerConfig, type MCPServerHandle, type SimulationWithDist } from './types.js';

export type { MCPServerConfig, MCPServerHandle, SimulationWithDist } from './types.js';

// Dev server URLs for Vite HMR (localhost only — used for direct connections like ChatGPT)
const LOCAL_DEV_SERVER_URL = 'http://localhost:8000';
const LOCAL_HMR_WS_URL = 'ws://localhost:24678';

/**
 * Detect whether this request needs pre-built HTML (no Vite HMR).
 *
 * Claude's iframe sandbox blocks HTTP script sources, so it can't load from the
 * local Vite dev server. We detect Claude by its user-agent and serve the
 * self-contained production build instead.
 *
 * ChatGPT also connects through tunnels but its browser can reach localhost via
 * the local-network-access permission, so it gets Vite HMR.
 */
function needsProdBuild(headers: Record<string, string | string[] | undefined>): boolean {
  const ua = headers['user-agent'];
  const userAgent = typeof ua === 'string' ? ua : Array.isArray(ua) ? ua[0] : '';
  return /claude/i.test(userAgent ?? '');
}

/**
 * Read pre-built resource HTML (production mode).
 * The HTML file is generated by `sunpeak build` with JS and CSS inlined.
 */
function readResourceHtmlProd(distPath: string): string {
  const htmlPath = path.resolve(distPath);

  if (!fs.existsSync(htmlPath)) {
    throw new Error(
      `Resource HTML file not found at ${htmlPath}. Run "sunpeak build" to generate the built app.`
    );
  }

  return fs.readFileSync(htmlPath, 'utf8');
}

/**
 * Generate HTML that loads from Vite dev server with HMR.
 * Used for direct connections (e.g. ChatGPT connecting to localhost).
 */
function getViteResourceHtml(srcPath: string): string {
  // Extract component name from path:
  //   /src/resources/albums/albums.tsx -> AlbumsResource
  const rawFileName = srcPath.split('/').pop() ?? '';
  const fileName = rawFileName.replace(/\.tsx$/, '');
  const componentName =
    fileName
      .split('-')
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join('') + 'Resource';

  const devServerUrl = LOCAL_DEV_SERVER_URL;

  // Encode srcPath and componentName for the virtual entry module
  const entryParams = new URLSearchParams({ src: srcPath, component: componentName });
  // Vite serves virtual modules via /@id/ prefix
  const virtualModuleUrl = `${devServerUrl}/@id/virtual:sunpeak-entry?${entryParams.toString()}`;

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <script type="module">
    import { injectIntoGlobalHook } from "${devServerUrl}/@react-refresh";
    injectIntoGlobalHook(window);
    window.$RefreshReg$ = () => {};
    window.$RefreshSig$ = () => (type) => type;
    window.__vite_plugin_react_preamble_installed__ = true;
  </script>
  <script type="module" src="${devServerUrl}/@vite/client"></script>
  <script type="module">
    (async () => {
      if (!navigator.permissions?.query) return;
      const protocol = window.location.protocol;
      if (protocol !== 'http:' && protocol !== 'https:') return;
      const host = window.location.hostname;
      const isLoopback = host === 'localhost' || /^127\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})$/.test(host) || host === '::1';
      if (isLoopback) return;
      try {
        const status = await navigator.permissions.query({ name: "local-network-access" });
        if (status.state === "denied") {
          document.getElementById('root').innerHTML = '<div style="background:#fef2f2;border:2px solid #ef4444;border-radius:8px;padding:16px;text-align:center;font-family:system-ui,sans-serif;"><div style="color:#ef4444;font-size:18px;font-weight:600;margin-bottom:8px;">Local network access permission is denied</div><div style="color:#ef4444;font-size:14px;">Please enable it in your browser settings. <a href="https://developer.chrome.com/blog/local-network-access" target="_blank" style="color:#ef4444;text-decoration:underline;">Learn more</a></div></div>';
        }
      } catch (e) {}
    })();
  </script>
  <div id="root"></div>
  <script type="module" src="${virtualModuleUrl}"></script>
</body>
</html>`;
}

/**
 * Get resource HTML content.
 *
 * - Direct connections (ChatGPT): Vite dev server HTML with HMR
 * - Tunnel connections (Claude via ngrok): Pre-built HTML with everything inlined
 */
function getResourceHtml(
  simulation: SimulationWithDist,
  viteMode: boolean,
  prodBuild: boolean
): string {
  if (viteMode && simulation.srcPath && !prodBuild) {
    return getViteResourceHtml(simulation.srcPath);
  }
  return readResourceHtmlProd(simulation.distPath);
}

/**
 * Inject localhost Vite dev server URLs into CSP metadata.
 * Only needed for direct connections where the iframe loads scripts from localhost.
 */
function injectViteCSP(existingMeta: Record<string, unknown> | undefined): Record<string, unknown> {
  const meta = existingMeta ?? {};
  const ui = (meta.ui as Record<string, unknown>) ?? {};
  const csp = (ui.csp as Record<string, unknown>) ?? {};

  const existingResourceDomains = (csp.resourceDomains as string[]) ?? [];
  const resourceDomains = existingResourceDomains.includes(LOCAL_DEV_SERVER_URL)
    ? existingResourceDomains
    : [...existingResourceDomains, LOCAL_DEV_SERVER_URL];

  const existingConnectDomains = (csp.connectDomains as string[]) ?? [];
  const connectDomains = [...existingConnectDomains];
  if (!connectDomains.includes(LOCAL_DEV_SERVER_URL)) connectDomains.push(LOCAL_DEV_SERVER_URL);
  if (!connectDomains.includes(LOCAL_HMR_WS_URL)) connectDomains.push(LOCAL_HMR_WS_URL);

  return {
    ...meta,
    ui: {
      ...ui,
      csp: { ...csp, resourceDomains, connectDomains },
    },
  };
}

type AppServerResult = {
  server: McpServer;
  resourceHandles: Map<string, RegisteredResource>;
  toolHandles: {
    handle: RegisteredTool;
    resourceName: string;
    toolMeta: Record<string, unknown>;
  }[];
};

function createAppServer(
  config: MCPServerConfig,
  simulations: SimulationWithDist[],
  viteMode: boolean
): AppServerResult {
  const { name = 'sunpeak-app', version = '0.1.0' } = config;

  const mcpServer = new McpServer(
    {
      name,
      version,
      icons: [
        {
          src: `data:image/png;base64,${FAVICON_BASE64}`,
          mimeType: 'image/png',
          sizes: ['128x128'],
        },
      ],
    },
    { capabilities: { resources: {}, tools: {} } }
  );

  // Track registered resource URIs to avoid duplicate registration
  // (multiple simulations can share the same resource, e.g. review-diff and review-post)
  const registeredUriSet = new Set<string>();
  const resourceHandles = new Map<string, RegisteredResource>();
  const toolHandles: AppServerResult['toolHandles'] = [];

  // Register each simulation's tool and resource
  for (const simulation of simulations) {
    const resource = simulation.resource;
    const tool = simulation.tool;
    const toolResult = simulation.toolResult ?? { structuredContent: null };

    // Use the resource's URI, or derive a stable one from the resource name.
    // Must be stable across all sessions — ChatGPT reads resource URIs from the tools/list
    // response in one session, then fetches the content in a separate resources/read session.
    const uri = (resource.uri as string) ?? `ui://${resource.name as string}`;
    const resourceName = resource.name as string;
    const resourceMeta = (resource._meta as Record<string, unknown>) ?? {};
    const toolMeta = (tool._meta as Record<string, unknown>) ?? {};

    // Register the resource directly via SDK (not ext-apps wrapper) to capture the
    // RegisteredResource handle for URI updates on rebuild (cache-busting).
    if (!registeredUriSet.has(uri)) {
      registeredUriSet.add(uri);
      const listMeta = viteMode ? injectViteCSP(resourceMeta) : resourceMeta;
      console.log(`[MCP] RegisterResource: ${uri}`);
      const handle = mcpServer.registerResource(
        resourceName,
        uri,
        {
          mimeType: RESOURCE_MIME_TYPE,
          description: resource.description as string | undefined,
          _meta: listMeta,
        },
        async (
          readUri: URL,
          extra: { requestInfo?: { headers?: Record<string, string | string[] | undefined> } }
        ) => {
          // Claude's sandbox blocks HTTP script sources, so serve pre-built HTML.
          // ChatGPT can reach localhost, so it gets Vite HMR.
          const prodBuild = needsProdBuild(
            (extra?.requestInfo?.headers as Record<string, string | string[] | undefined>) ?? {}
          );
          const readMeta = viteMode && !prodBuild ? injectViteCSP(resourceMeta) : resourceMeta;

          let content: string;
          try {
            content = getResourceHtml(simulation, viteMode, prodBuild);
          } catch (error) {
            console.error(`[MCP] ReadResource error for ${readUri.href}:`, error);
            throw error;
          }
          const sizeKB = (content.length / 1024).toFixed(1);
          console.log(
            `[MCP] ReadResource: ${readUri.href} → ${sizeKB}KB${prodBuild ? ' (prod build)' : ' (vite)'}`
          );

          return {
            contents: [
              {
                // Use readUri (not closure variable) so the response URI matches after updates
                uri: readUri.href,
                mimeType: RESOURCE_MIME_TYPE,
                text: content,
                _meta: readMeta,
              },
            ],
          };
        }
      );
      resourceHandles.set(resourceName, handle);
    }

    // Register the tool using ext-apps helper (normalizes ui/resourceUri metadata).
    // Capture the returned RegisteredTool handle for metadata updates on rebuild.
    // Note: inputSchema from simulation is JSON Schema, not Zod, so we omit it here
    // (simulation mode doesn't validate inputs - just logs what was called)
    const fullToolMeta = {
      ...toolMeta,
      ui: {
        resourceUri: uri,
        // Preserve tool visibility from simulation metadata if declared
        ...((toolMeta.ui as Record<string, unknown>)?.visibility
          ? { visibility: (toolMeta.ui as Record<string, unknown>).visibility }
          : {}),
      },
    };
    const toolHandle = registerAppTool(
      mcpServer,
      tool.name as string,
      {
        description: tool.description as string | undefined,
        _meta: fullToolMeta,
      },
      async (extra) => {
        // Access arguments from request context (no inputSchema = no parsed args)
        const args =
          (extra as { request?: { params?: { arguments?: Record<string, unknown> } } }).request
            ?.params?.arguments ?? {};
        const argKeys = Object.keys(args);
        const argsStr = argKeys.length > 0 ? `{${argKeys.join(', ')}}` : '{}';
        const hasStructuredContent = toolResult?.structuredContent != null;

        console.log(
          `[MCP] CallTool: ${tool.name}${argsStr} → ${hasStructuredContent ? 'structured' : 'text'}`
        );

        return {
          content: [
            {
              type: 'text' as const,
              text: `Rendered ${tool.description}!`,
            },
          ],
          structuredContent:
            (toolResult?.structuredContent as Record<string, unknown>) ?? undefined,
        };
      }
    );
    toolHandles.push({ handle: toolHandle, resourceName, toolMeta: fullToolMeta });
  }

  const registeredUris = Array.from(registeredUriSet).join(', ');
  console.log(
    `[MCP] Registered ${simulations.length} tool(s) and resource(s)${viteMode ? ' (vite mode)' : ''}: ${registeredUris}`
  );

  return { server: mcpServer, resourceHandles, toolHandles };
}

type SessionRecord = {
  server: McpServer;
  transport: StreamableHTTPServerTransport;
  /** True for localhost connections (ChatGPT, simulator) — they use Vite HMR. */
  isLocal: boolean;
  lastActivity: number;
  /** Resource handles for URI cache-busting on rebuild. Keyed by resource name. */
  resourceHandles: Map<string, RegisteredResource>;
  /** Tool handles for metadata cache-busting on rebuild. */
  toolHandles: AppServerResult['toolHandles'];
};

/** How long an idle session lives before being cleaned up (5 minutes). */
const SESSION_IDLE_TIMEOUT_MS = 5 * 60 * 1000;

/**
 * Check if the request originates from localhost.
 * Local connections (ChatGPT, simulator) use Vite HMR for live content updates.
 */
function isLocalConnection(req: IncomingMessage): boolean {
  const addr = req.socket.remoteAddress;
  return addr === '127.0.0.1' || addr === '::1' || addr === '::ffff:127.0.0.1';
}

const sessions = new Map<string, SessionRecord>();

const MCP_PATH = '/mcp';

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS',
  'Access-Control-Allow-Headers':
    'content-type, accept, authorization, mcp-session-id, ngrok-skip-browser-warning',
  'Access-Control-Expose-Headers': 'mcp-session-id',
} as const;

// Periodically clean up idle sessions.
// Closing the server triggers transport.onclose which handles session map cleanup.
const cleanupInterval = setInterval(() => {
  const now = Date.now();
  for (const [id, session] of sessions) {
    if (now - session.lastActivity > SESSION_IDLE_TIMEOUT_MS) {
      console.log(`[MCP] Session expired: ${id.substring(0, 8)}...`);
      void session.server.close();
    }
  }
}, 60_000);
cleanupInterval.unref();

async function handleMcpRequest(
  req: IncomingMessage,
  res: ServerResponse,
  config: MCPServerConfig,
  simulations: SimulationWithDist[],
  viteMode: boolean
) {
  // Set CORS headers for all MCP responses
  for (const [key, value] of Object.entries(CORS_HEADERS)) {
    res.setHeader(key, value);
  }

  // Parse body for POST requests
  let parsedBody: unknown;
  if (req.method === 'POST') {
    const chunks: Buffer[] = [];
    await new Promise<void>((resolve, reject) => {
      req.on('data', (chunk: Buffer | string) => {
        chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk as string));
      });
      req.on('end', resolve);
      req.on('error', reject);
    });
    const rawBody = Buffer.concat(chunks).toString('utf8');
    try {
      parsedBody = JSON.parse(rawBody);
      const parsed = parsedBody as { method?: string; params?: Record<string, unknown> };
      if (parsed.method) {
        const sid = req.headers['mcp-session-id'] as string | undefined;
        const sidStr = sid ? ` (${sid.substring(0, 8)}...)` : '';
        const extra =
          parsed.method === 'resources/read' ? ` uri=${JSON.stringify(parsed.params?.uri)}` : '';
        console.log(`[MCP] ← ${parsed.method}${extra}${sidStr}`);
      }
    } catch {
      res.writeHead(400).end('Invalid JSON');
      return;
    }
  }

  const sessionId = req.headers['mcp-session-id'] as string | undefined;

  // Route to existing session
  if (sessionId) {
    const session = sessions.get(sessionId);
    if (!session) {
      res.writeHead(404).end('Unknown session');
      return;
    }
    session.lastActivity = Date.now();
    await session.transport.handleRequest(req, res, parsedBody);
    return;
  }

  // New session (POST without session ID = initialization)
  if (req.method === 'POST') {
    const isLocal = isLocalConnection(req);
    const { server, resourceHandles, toolHandles } = createAppServer(config, simulations, viteMode);
    const transport = new StreamableHTTPServerTransport({
      sessionIdGenerator: () => randomUUID(),
      onsessioninitialized: (id) => {
        sessions.set(id, {
          server,
          transport,
          isLocal,
          lastActivity: Date.now(),
          resourceHandles,
          toolHandles,
        });
        const origin = isLocal ? 'local' : 'tunnel';
        console.log(
          `[MCP] Session started: ${id.substring(0, 8)}... (${origin}, ${sessions.size} active)`
        );
      },
      onsessionclosed: (id) => {
        sessions.delete(id);
        console.log(`[MCP] Session closed: ${id.substring(0, 8)}... (${sessions.size} active)`);
      },
    });

    transport.onerror = (error: Error) => {
      const id = transport.sessionId;
      console.error(`[MCP] Transport error${id ? ` (${id.substring(0, 8)}...)` : ''}:`, error);
    };

    transport.onclose = () => {
      const id = transport.sessionId;
      if (id && sessions.has(id)) {
        sessions.delete(id);
        console.log(`[MCP] Session closed: ${id.substring(0, 8)}... (${sessions.size} active)`);
      }
    };

    await server.connect(transport);
    await transport.handleRequest(req, res, parsedBody);
    return;
  }

  // No session ID and not POST → invalid
  res.writeHead(400).end('Bad Request: session ID required');
}

// Type for Vite dev server (minimal interface we need)
interface ViteDevServer {
  middlewares: {
    (req: IncomingMessage, res: ServerResponse, next?: () => void): void;
  };
  ws: {
    handleUpgrade: (
      request: IncomingMessage,
      socket: import('node:stream').Duplex,
      head: Buffer
    ) => void;
  };
}

/**
 * Run the MCP server with the specified configuration.
 *
 * @param config - Server configuration with simulations.
 * @returns Handle for controlling the running server (e.g. cache invalidation).
 */
export function runMCPServer(config: MCPServerConfig): MCPServerHandle {
  const portEnv = Number(process.env.PORT ?? 8000);
  const port = config.port ?? (Number.isFinite(portEnv) ? portEnv : 8000);
  const { simulations } = config;

  // Check if Vite dev server is provided
  const viteServer = config.viteServer as ViteDevServer | undefined;
  const viteMode = !!viteServer;

  const httpServer = createServer(async (req: IncomingMessage, res: ServerResponse) => {
    if (!req.url) {
      res.writeHead(400).end('Missing URL');
      return;
    }

    const url = new URL(req.url, `http://${req.headers.host ?? 'localhost'}`);

    // CORS preflight for all routes
    if (req.method === 'OPTIONS') {
      res.writeHead(204, CORS_HEADERS);
      res.end();
      return;
    }

    // Root path (ChatGPT checks this before fetching favicon)
    if (req.method === 'GET' && url.pathname === '/') {
      res.writeHead(200, {
        'Content-Type': 'text/html',
        'Access-Control-Allow-Origin': '*',
      });
      res.end(`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<link rel="icon" type="image/png" href="/favicon.ico" />
<title>Sunpeak MCP Server</title>
</head>
<body><h1>Sunpeak MCP Server</h1><p>Connect via <a href="/mcp">/mcp</a></p></body>
</html>`);
      return;
    }

    // Favicon endpoint
    if (req.method === 'GET' && url.pathname === '/favicon.ico') {
      res.writeHead(200, {
        'Content-Type': 'image/png',
        'Content-Length': FAVICON_BUFFER.length,
        'Cache-Control': 'public, max-age=86400',
        'Access-Control-Allow-Origin': '*',
      });
      res.end(FAVICON_BUFFER);
      return;
    }

    // MCP endpoint (Streamable HTTP transport)
    if (url.pathname === MCP_PATH) {
      await handleMcpRequest(req, res, config, simulations, viteMode);
      return;
    }

    // If Vite server is available, delegate all other requests to it
    if (viteServer) {
      // Add CORS headers for Vite-served content (needed for cross-origin widget loading)
      res.setHeader('Access-Control-Allow-Origin', '*');
      res.setHeader('Access-Control-Allow-Headers', 'content-type, ngrok-skip-browser-warning');
      viteServer.middlewares(req, res);
      return;
    }

    // No Vite server, return 404 for non-MCP routes
    console.log(`[HTTP] ${req.method} ${url.pathname} → 404`);
    res.writeHead(404).end('Not Found');
  });

  // Handle WebSocket upgrades for Vite HMR
  if (viteServer) {
    httpServer.on('upgrade', (request, socket, head) => {
      // Forward all WebSocket upgrades to Vite (it handles /@vite/ws)
      viteServer.ws.handleUpgrade(request, socket, head);
    });
  }

  httpServer.on('clientError', (err: Error, socket) => {
    console.error('HTTP client error', err);
    socket.end('HTTP/1.1 400 Bad Request\r\n\r\n');
  });

  httpServer.listen(port, () => {
    console.log(`Sunpeak MCP server listening on http://localhost:${port}`);
    console.log(`  MCP endpoint: http://localhost:${port}${MCP_PATH}`);
    if (viteMode) {
      console.log(`  Vite HMR: enabled (source files served with hot reload)`);
    }
  });

  // Graceful shutdown handler
  const shutdown = async () => {
    console.log('\nShutting down MCP server...');

    httpServer.close(() => {
      console.log('MCP server closed');
      process.exit(0);
    });

    // Force close after 5 seconds if graceful shutdown fails
    setTimeout(() => {
      console.error('Force closing MCP server');
      process.exit(1);
    }, 5000);
  };

  process.on('SIGTERM', () => void shutdown());
  process.on('SIGINT', () => void shutdown());

  return {
    invalidateResources() {
      if (sessions.size === 0) return;

      const timestamp = Date.now();
      for (const [, session] of sessions) {
        // Update resource URIs with timestamp to force cache-busting.
        // .update() automatically sends resources/list_changed notification.
        for (const [name, handle] of session.resourceHandles) {
          handle.update({ uri: `ui://${name}-${timestamp}` });
        }
        // Update tool metadata to reference the new resource URIs.
        // .update() automatically sends tools/list_changed notification.
        for (const { handle, resourceName, toolMeta } of session.toolHandles) {
          const newUri = `ui://${resourceName}-${timestamp}`;
          handle.update({
            _meta: {
              ...toolMeta,
              ui: { ...(toolMeta.ui as Record<string, unknown>), resourceUri: newUri },
              'ui/resourceUri': newUri,
            },
          });
        }
      }
      console.log(`[MCP] Cache-busted ${sessions.size} session(s) with timestamp ${timestamp}`);
    },
  };
}
